name: Merge downstream

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Verify branch"]
    types: [completed] #requested
    branches: [release/2.6, release/2.7, release/2.8, waitJob_195]

env:
  downstream_release/2.6: release/2.7
  downstream_release/2.7: release/2.8
  downstream_release/2.8: master
  downstream_waitJob_195: waitJob_2.7_195

run-name: Merge ${{ github.event.workflow_run.head_branch }} downstream 

jobs:
  pull_request:  
    permissions:
      pull-requests: write
      contents: write
      actions: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: create pull request
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          for i in ${{ env[format('downstream_{0}', github.event.workflow_run.head_branch)] }} ; do
            devenv/scripts/verify_merge.sh "${{ github.event.workflow_run.head_branch }}" "${{ github.event.workflow_run.head_sha }}" "$i" "[Created by Github action](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})"
          done
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
